### ISSUE TITLE
Enhancement: Make the Factory Map start in PAN-Mode

### ISSUE THREAD

**Issue by MrJulsen** [tvwenger/du-factory-generator#100]
Make the default mode for the Factory Map the PAN-Mode.

**Comment by tvwenger** [comment]
Thanks for the suggestion! I'll try to get this implemented in the next version release.

**Comment by tvwenger** [comment]
Alright, this was not as easy as it sounded. I had to submit a PR to get the typings right for `react-svg-pan-zoom`: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57909

In the meantime, I have pushed a hack that implements "pan" as the default tool in the next version!

https://github.com/tvwenger/du-factory-generator/pull/108
