### ISSUE TITLE
Pure Names are inconsistent

### ISSUE THREAD

**Issue by MrJulsen** [tvwenger/du-factory-generator#102]
they still come from an earlier game version where they have been inconsistent aswell.
now they should all be called 'Pure Aluminium' instead of 'Aluminium Pure'.

Typing 'pure' in the new factory page shows what is outdated.

**Comment by tvwenger** [comment]
Thanks for letting me know!

**Comment by tvwenger** [comment]
Fixed by https://github.com/tvwenger/du-factory-generator/pull/105
