### ISSUE TITLE
Error loading pre-existing factory

### ISSUE THREAD

**Issue by MarcoPolo09** [tvwenger/du-factory-generator#92]
Not sure whats causing the error but we have previously created a factory plan etc using the website no problems however now when we try to reload it it keeps going start to an error message as per the attached 
![image](https://user-images.githubusercontent.com/79897643/132443752-df2a4f15-3b64-453c-b766-d5ec55c91a44.png)
![Capture](https://user-images.githubusercontent.com/79897643/132443788-36355952-b1d2-4be7-b593-d1c5d4195be5.JPG)

**Comment by tvwenger** [comment]
Thanks for reporting! Could you please send me your previous factory plan? You could DM me on Discord or upload it somewhere and post a link here.

**Comment by MarcoPolo09** [comment]
Hi mate, yeah happy to send you the factory Json I tried searching you in discord but couldn't find you on any common servers strangely.
If you can maybe DM me I should be easy enough to find but the tag is MarcoPolo#2183

**Comment by tvwenger** [comment]
Closing since we've made some serious updates in the upcoming v4.0. If you still encounter these problems, please let me know!
